@echo off
echo Starting Netflix Clone Server...
cd /d "c:\Users\rohit\OneDrive\Documents\netflix clone\netflix-clone"
echo Killing any existing Node processes...
taskkill /F /IM node.exe >nul 2>&1
echo Starting test server...
node test-server.js
pause
